name: minmod

services:
  kg:
    image: minmod-fuseki
    build:
      context: ./containers/fuseki/
      args:
        UID: ${USER_ID}
        GID: ${GROUP_ID}
  etl:
    image: minmod-etl
    build: 
      context: .
      dockerfile: containers/etl/Dockerfile
      args:
        UID: ${USER_ID}
        GID: ${GROUP_ID}