version: 1

services:
  - name: kg.data.entities
    classpath: statickg.services.drepr.DReprService
    args:
      path:
        - ::CFG_DIR::extractors/category.yml
        - ::CFG_DIR::extractors/commodity.yml
        - ::CFG_DIR::extractors/deposit_type.yml
        - ::CFG_DIR::extractors/unit.yml
        - ::CFG_DIR::extractors/country.yml
        - ::CFG_DIR::extractors/state_or_province.yml
        - ::CFG_DIR::extractors/source.yml
        - ::CFG_DIR::extractors/epsg.yml
        - ::CFG_DIR::extractors/material_form.yml
      format: turtle
  - name: kg.data.same_as
    classpath: minmodkg.etl.same_as.SameAsService
  - name: kg.data.mineral_site
    classpath: statickg.services.drepr.DReprService
    args:
      path: ::CFG_DIR::extractors/mineral_site.yml
      format: turtle
      parallel: true
  - name: kg.data.source_mineral_site
    classpath: minmodkg.etl.source.SourceService
    args:
      parallel: true
  - name: kg.views.mineral_site
    classpath: minmodkg.etl.mineral_site_view.MineralSiteViewService
    args:
      parallel: true
  - name: copy
    classpath: statickg.services.copy.CopyService
  - name: version
    classpath: statickg.services.version.VersionService
  - name: concat
    classpath: statickg.services.concat.ConcatTTLService
  - name: validate filename
    classpath: minmodkg.validators.FilenameValidatorService
    args:
      pattern: ^[a-zA-Z0-9_\-,.]+$
  - name: kgrel.data.mineral_site
    classpath: minmodkg.etl.mineral_site.MineralSiteETLService
    args:
      parallel: true
  - name: kg.loader.fuseki
    classpath: minmodkg.etl.fuseki.FusekiLoaderService
    args:
      capture_output: false
      dbdir: "::DB_DIR::kg"
      find_by_id: docker ps --format '{{{{index (split .Ports "-") 0}}}}' --filter name={ID}
      start_service: >-
        docker run --name {ID}
        -d -p {PORT}:3030
        -v {DB_DIR}:/home/criticalmaas/databases
        -v ::DATA_DIR::{}:/data
        --network=minmod
        --network-alias=kg
        minmod-fuseki fuseki/fuseki-server --config=fuseki/config.ttl
      stop_service: docker stop {ID} && docker rm {ID}
      load_cmd: >-
        docker run --rm --name {ID}
        -v {DB_DIR}:/home/criticalmaas/databases
        -v ::DATA_DIR::{}:/data
        -w /data
        minmod-fuseki mytdbloader --loc /home/criticalmaas/databases /data/{INPUT_FILE_LST}
  - name: kg.loader.blazegraph
    classpath: minmodkg.etl.blazegraph.BlazeGraphLoaderService
    args:
      capture_output: false
      dbdir: "::DB_DIR::kg"
      find_by_id: docker ps --format '{{{{index (split .Ports "-") 0}}}}' --filter name={ID}
      start_service: >-
        docker run --name {ID}
        -d -p {PORT}:9999
        -v {DB_DIR}:/home/criticalmaas/database
        -v ::DATA_DIR::{}:/data
        --network=minmod
        --network-alias=kg
        minmod-blazegraph
      stop_service: docker stop {ID} && docker rm {ID}
      load_cmd: >-
        docker run --rm --name {ID}
        -v {DB_DIR}:/home/criticalmaas/database
        -v ::DATA_DIR::{}:/data
        minmod-blazegraph python3 /home/criticalmaas/data_loader.py /data/{INPUT_FILE_LST}
  - name: kg.loader.virtuoso
    classpath: minmodkg.etl.virtuoso.VirtuosoLoaderService
    args:
      capture_output: false
      dbdir: "::DB_DIR::kg"
      find_by_id: docker ps --format '{{{{index (split .Ports "-") 0}}}}' --filter name={ID}
      start_service: >-
        docker run --name {ID}
        -d -p {PORT}:8890
        -v {DB_DIR}:/database
        -v ::DATA_DIR::{}:/criticalmaas/kgdata
        --network=minmod
        --network-alias=kg
        minmod-virtuoso
      stop_service: docker stop {ID} && docker rm {ID}
      load_cmd: docker exec {ID} python3 /criticalmaas/build/data_loader.py /criticalmaas/kgdata/{INPUT_FILE_LST}
  - name: kg.loader.postgres
    classpath: minmodkg.etl.postgres.PostgresLoaderService
    args:
      capture_output: false
      dbdir: "::DB_DIR::kgrel"
      find_by_id: docker ps --format '{{{{index (split .Ports "-") 0}}}}' --filter name={ID}
      start_service: >-
        docker run --name {ID}
        -d -p {PORT}:5432
        -v {DB_DIR}:/database
        --shm-size=1G
        --network=minmod
        --network-alias=kg-postgres
        minmod-postgres
      stop_service: docker stop {ID} && docker rm {ID}
      load_cmd: "" # postgres does not need to load data
pipeline:
  - service: validate filename
    args:
      input:
        - ::REPO::data/entities/*.csv
        - ::REPO::data/mineral-sites/*/*/*.json
        - ::REPO::data/same-as/umn/*.csv
        - ::REPO::data/mappable-criteria/sri/*.json
        - ::REPO::data/curated-mineral-sites/*/*/*.json
  - service: kg.data.entities
    args:
      input: ::REPO::data/entities/*.csv
      output: ::DATA_DIR::predefined-entities/
  - service: kg.data.mineral_site
    args:
      - input: ::REPO::data/mineral-sites/*/*/*.json
        output:
          base: ::DATA_DIR::mineral-sites
          format: "{filegrandparent}/{fileparent}_{filestem}.{fileext}"
  - service: kg.data.same_as
    args:
      input: ::REPO::data/same-as/umn/*.csv
      curated_input: ::REPO::data/curated-same-as/*/*.json
      output:
        base: ::DATA_DIR::same-as/
        format: "{fileparent}_{filestem}.json"
  - service: kgrel.data.mineral_site
    args:
      input: ::REPO::data/mineral-sites/*/*/*.json
      output: ::DATA_DIR::relation-mineral-sites
      predefined_entity_dir: ::DATA_DIR::predefined-entities/
      same_as_group: ::DATA_DIR::same-as/final/groups.json
  - service: kg.data.source_mineral_site
    args:
      input: ::REPO::data/mineral-sites/*/*/*.json
      output:
        base: ::DATA_DIR::mineral-site-sources
        format: "{filegrandparent}/{fileparent}_{filestem}.json"
      predefined_entities: ::DATA_DIR::predefined-entities/
      default_source_score: 0.5
  # - service: kg.views.mineral_site
  #   args:
  #     predefined_entities: ::DATA_DIR::predefined-entities/
  #     same_as_group: ::DATA_DIR::same-as/final/groups.json
  #     input: ::REPO::data/mineral-sites/*/*/*.json
  #     output:
  #       base: ::DATA_DIR::view-mineral-sites/
  #       format: "{filegrandparent}/{fileparent}_{filestem}.json"
  - service: copy
    args:
      input: ::CFG_DIR::schema/ontology.ttl
      output: "::DATA_DIR::"
  - service: version
    args:
      entity: https://minmod.isi.edu/resource/kg
      entity_type: https://minmod.isi.edu/ontology/KnowledgeGraph
      output: ::DATA_DIR::version.ttl
  - service: kg.loader.fuseki
    # service: kg.loader.blazegraph
    # - service: kg.loader.virtuoso
    args:
      input:
        - ::DATA_DIR::ontology.ttl
        - ::DATA_DIR::predefined-entities/*.ttl
        - ::DATA_DIR::mineral-sites/*/*.ttl
        - ::DATA_DIR::same-as/final/*.ttl
        - ::DATA_DIR::dedup-mineral-sites/final/*.ttl
        - ::DATA_DIR::mineral-site-sources/final/*.ttl
      replaceable_input: ::DATA_DIR::version.ttl
      deploy: { port: 3030 }
  - service: kg.loader.postgres
    args:
      input:
        - ::DATA_DIR::relation-mineral-sites/merged/**/*.json*
      deploy: { port: 5432 }
