version: 1

services:
  - name: predefined entities
    classpath: statickg.services.drepr.DReprService
    args:
      path:
        - ::CFG_DIR::extractors/category.yml
        - ::CFG_DIR::extractors/commodity.yml
        - ::CFG_DIR::extractors/deposit_type.yml
        - ::CFG_DIR::extractors/unit.yml
        - ::CFG_DIR::extractors/country.yml
        - ::CFG_DIR::extractors/state_or_province.yml
        - ::CFG_DIR::extractors/epsg.yml
      format: turtle
  - name: same as
    classpath: statickg.services.drepr.DReprService
    args:
      path: ::CFG_DIR::extractors/same_as.yml
      format: turtle
  - name: mineral site
    classpath: statickg.services.drepr.DReprService
    args:
      path: ::CFG_DIR::extractors/mineral_site.yml
      format: turtle
  - name: mineral system
    classpath: statickg.services.drepr.DReprService
    ext: ttl
    args:
      path: ::CFG_DIR::extractors/mineral_system.yml
      format: turtle
  - name: copy
    classpath: statickg.services.copy.CopyService
  - name: version
    classpath: statickg.services.version.VersionService
  - name: load to fuseki
    classpath: statickg.services.fuseki.FusekiDataLoaderService
    args:
      batch_size: 128

pipeline:
  - service: predefined entities
    args:
      input: ::REPO::data/entities/*.csv
      output: ::DATA_DIR::predefined-entities/
  - service: mineral site
    args:
      - input: ::REPO::data/inferlink/extractions/*.json
        output: ::DATA_DIR::mineral-sites/inferlink/
      - input: ::REPO::data/umn/*.json
        output: ::DATA_DIR::mineral-sites/umn/
      - input: ::REPO::data/sri/*.json
        output: ::DATA_DIR::mineral-sites/sri/
  - service: same as
    args:
      input: ::REPO::data/umn/sameas/*.csv
      output: ::DATA_DIR::same-as/
  - service: mineral system
    args:
      input: ::REPO::data/sri/mappableCriteria/*.json
      output: ::DATA_DIR::mappable-criteria/
  - service: copy
    args:
      input: ::REPO::data/usc/*.ttl
      output: ::DATA_DIR::usc/
  - service: version
    args:
      entity: https://minmod.isi.edu/resource/kg
      entity_type: https://minmod.isi.edu/resource/KnowledgeGraph
      output: ::DATA_DIR::version.ttl
  # - service: load to fuseki
  #   args:
  #     input: ::DATA_DIR::*/**/*.ttl
  #     input_basedir: "::DATA_DIR::"
  #     dbdir: "::DB_DIR::"
  #     endpoint:
  #       update: http://localhost:3030/minmod/update
  #       gsp: http://localhost:3030/minmod/data
  #     replaceable_input: ::DATA_DIR::version.ttl
  #     command: >-
  #       docker run --rm -it -w /data
  #       -v {DB_DIR}:/databases
  #       -v ::DATA_DIR::{}:/data
  #       minmod-fuseki /opt/jena/bin/tdb2.tdbloader --loc /databases {FILES}
